import Link from 'next/link'
import { H1, H2, H3, P, Small, Muted } from '@/components/typography'
import { OnThisPage } from '@/components/docs/on-this-page'

export const metadata = {
  title: 'How AI Features Work',
  description: 'Moderation, Summaries, and Privacy in the AI Chat Forum',
}

export default function AIFeaturesDocs() {
  return (
    <main className='container mx-auto px-4 sm:px-6 lg:px-8 py-6 md:py-10 grid gap-8 lg:gap-12 md:grid-cols-[minmax(0,1fr)_260px]'>
      {/* Content */}
      <article
        className='container-prose prose-headings:scroll-mt-24 space-y-10 md:space-y-14'
        id='main'
      >
        <H1 id='overview'>How AI Features Work</H1>
        <P>
          This app uses AI in two main places: <strong>Moderation</strong> and{' '}
          <strong>Summaries</strong>. Below you’ll find what’s analyzed, when it
          runs, what we store, and how you can opt out or report issues.
        </P>

        <H2 id='moderation'>1. Moderation</H2>
        <P>
          Every post is checked for policy violations (e.g., hate, harassment,
          self-harm, sexual content involving minors, spam). The moderation step
          happens in the background worker shortly after a post is created.
        </P>
        <H3 id='moderation-what-we-check'>What we check</H3>
        <ul className='list-disc list-inside space-y-2'>
          <li>Toxicity, harassment, hate/violence</li>
          <li>Personal data leaks & unsafe sharing</li>
          <li>Spam and suspicious link patterns</li>
        </ul>
        <H3 id='moderation-actions'>Possible actions</H3>
        <ul className='list-disc list-inside space-y-2'>
          <li>
            <strong>Allow</strong> — Post remains visible.
          </li>
          <li>
            <strong>Flag</strong> — Marked as <code>flagged</code> and moved to
            the Admin Moderation queue.
          </li>
          <li>
            <strong>Remove</strong> — Hidden from public views if it clearly
            violates policy.
          </li>
        </ul>
        <Muted>
          Note: Final decisions are human-reviewable in{' '}
          <Link href='/admin/moderation'>Admin → Moderation</Link>.
        </Muted>

        <H2 id='summaries'>2. Summaries</H2>
        <P>
          Long threads can be summarized to speed up catch-up. Summaries are
          generated by the worker from recent posts and updated periodically.
        </P>
        <H3 id='summaries-logic'>How it works</H3>
        <ul className='list-disc list-inside space-y-2'>
          <li>
            The worker batches recent posts and calls an AI summarizer (or your
            custom function).
          </li>
          <li>We prioritize author intent and thread context.</li>
          <li>Summaries never replace the original content.</li>
        </ul>
        <H3 id='summaries-limits'>Limitations</H3>
        <ul className='list-disc list-inside space-y-2'>
          <li>Summaries can miss nuance or humor.</li>
          <li>They should not be treated as authoritative.</li>
        </ul>

        <H2 id='privacy'>3. Privacy & Data Handling</H2>
        <P>
          We send only the <em>minimum necessary text</em> for moderation and
          summaries. We do not sell data. Logs are retained briefly for abuse
          prevention and debugging.
        </P>
        <ul className='list-disc list-inside space-y-2'>
          <li>
            <strong>Inputs</strong>: Post text, basic thread metadata (IDs,
            timestamps).
          </li>
          <li>
            <strong>Outputs</strong>: A moderation label/score or a short
            abstract summary.
          </li>
          <li>
            <strong>Retention</strong>: Configurable; default minimal retention
            for ops.
          </li>
        </ul>

        <H2 id='controls'>4. User Controls</H2>
        <ul className='list-disc list-inside space-y-2'>
          <li>
            <strong>Report content</strong> via post menu → “Report”. Goes to
            Admin queue.
          </li>
          <li>
            <strong>Hide summaries</strong> in Settings → Preferences.
          </li>
          <li>
            <strong>Export data</strong> or request deletion in Settings →
            Account.
          </li>
        </ul>

        <H2 id='safety'>5. Safety & Rate Limits</H2>
        <P>
          To keep the system stable and fair, AI features use rate limits and
          back-off. When demand is high, summaries may be delayed and moderation
          relies on cached classifiers.
        </P>
        <ul className='list-disc list-inside space-y-2'>
          <li>Per-user and per-thread quotas (configurable).</li>
          <li>Automatic retries with jitter when providers fail.</li>
          <li>Clear error states in the UI with toasts and empty states.</li>
        </ul>

        <H2 id='implementation'>6. Implementation Notes</H2>
        <ul className='list-disc list-inside space-y-2'>
          <li>
            Moderation + summary jobs are queued with <code>bullmq</code>.
          </li>
          <li>
            Realtime updates (e.g., new posts) are delivered via Socket.IO
            events like <code>post:new</code>.
          </li>
          <li>
            Server code lives in <code>services/api</code>, workers in{' '}
            <code>services/worker</code>.
          </li>
          <li>
            Client calls use the axios instance in <code>lib/api.ts</code>.
          </li>
        </ul>

        <H2 id='contact'>7. Questions or Feedback</H2>
        <P>
          If something looks off, please contact the moderators or open an issue
          in your project repo. You can also disable summaries in Settings if
          preferred.
        </P>

        <Small className='block mt-8'>
          Last updated: {new Date().toLocaleDateString()}
        </Small>
      </article>

      {/* On this page (sticky nav) */}
      <aside className='hidden md:block md:pl-3 lg:pl-6'>
        <OnThisPage
          items={[
            { href: '#overview', label: 'Overview' },
            { href: '#moderation', label: 'Moderation' },
            { href: '#summaries', label: 'Summaries' },
            { href: '#privacy', label: 'Privacy' },
            { href: '#controls', label: 'User Controls' },
            { href: '#safety', label: 'Safety & Rate Limits' },
            { href: '#implementation', label: 'Implementation Notes' },
            { href: '#contact', label: 'Questions / Feedback' },
          ]}
        />
      </aside>
    </main>
  )
}
